version: '3'
services:
  cart-app:
    build: .
    restart: always
    networks:
      - cart-network 
    ports:
      - "5000:5000"
    depends_on:
      - cart-db
    env_file:
      - .env.development

  cart-db:
    image: "postgres:9.5.14-alpine"
    restart: always
    volumes:
      - cart-volume:/var/lib/postgresql/data/
    networks:
      - cart-network 
    ports:
      - "5432:5432"
    env_file:
      - .env.development

volumes:
  cart-volume:

networks:
  cart-network:
