apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: sample-python-app
build:
  artifacts:
  - image: tjmaynes/python-shopping-cart-service
deploy:
  kubectl:
    manifests:
    - k8s/shopping-cart-common/secret.yml
    - k8s/shopping-cart-db/deployment.yml
    - k8s/shopping-cart-db/persistence.gke.yml
    - k8s/shopping-cart-db/persistence.local.yml
    - k8s/shopping-cart-db/service.yml
    - k8s/shopping-cart-service/deployment.yml
    - k8s/shopping-cart-service/service.yml
