apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-shopping-cart-service
spec:
  selector:
    matchLabels:
      app: shopping-cart-service
  replicas: 4
  template:
    metadata:
      labels:
        app: shopping-cart-service
    spec:
      containers:
        - name: python-shopping-cart-service 
          image: tjmaynes/python-shopping-cart-service:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: python-shopping-cart-service
                  key: db-uri
            - name: FLASK_APP
              value: "python-shopping-cart-service"
