apiVersion: v1
kind: Secret
metadata:
  name: shopping-cart-secrets
type: Opaque
stringData:
  db-name: cart 
  db-username: root
  db-password: password
  db-uri: postgres://root:password@shopping-cart-db/cart?sslmode=disable
